"use client";

import { useMemo, useState } from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Overlay } from "@/types";

export function OverlayViewer({
  imageUrl,
  overlays
}: {
  imageUrl: string;
  overlays: Overlay[];
}) {
  const [showOverlays, setShowOverlays] = useState(true);
  const defaultSize = useMemo(() => ({ width: 720, height: 520 }), []);

  return (
    <Card className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-xl font-semibold text-slate-950">Imaging Panel</h3>
          <p className="mt-1 text-sm text-muted">Toggle estimated bounding boxes generated by the Vision Agent.</p>
        </div>
        <div className="flex items-center gap-3">
          <Badge>{overlays.length} overlays</Badge>
          <Button variant="outline" onClick={() => setShowOverlays((current) => !current)}>
            {showOverlays ? "Hide Overlays" : "Show Overlays"}
          </Button>
        </div>
      </div>

      <div className="relative overflow-hidden rounded-[2rem] border border-border bg-slate-950">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img alt="Chest X-ray" className="h-auto w-full object-contain" src={imageUrl} />
        {showOverlays
          ? overlays.map((overlay) => {
              const [x1, y1, x2, y2] = overlay.coords;
              return (
                <div
                  key={overlay.overlay_id}
                  className="absolute border-2 border-emerald-300 bg-emerald-300/10"
                  style={{
                    left: `${(x1 / defaultSize.width) * 100}%`,
                    top: `${(y1 / defaultSize.height) * 100}%`,
                    width: `${((x2 - x1) / defaultSize.width) * 100}%`,
                    height: `${((y2 - y1) / defaultSize.height) * 100}%`
                  }}
                >
                  <span className="absolute -top-7 left-0 rounded-full bg-emerald-300 px-3 py-1 text-xs font-semibold text-slate-950">
                    {overlay.label ?? overlay.overlay_id}
                  </span>
                </div>
              );
            })
          : null}
      </div>
    </Card>
  );
}
